services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GOLANG_VERSION: ${GOLANG_VERSION}
    ports:
      - ${APP_PORT}:8080
    environment:
      PORT: ${APP_PORT}
    volumes:
      - ../:/app
    restart: always
